version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www/php_test
    depends_on:
      - db
      - redis
   
  rabbitmq:
   image: rabbitmq:management
   container_name: rabbitmq
   ports:
     - "5672:5672"
     - "15672:15672"
   environment:
     RABBITMQ_DEFAULT_USER: user
     RABBITMQ_DEFAULT_PASS: password
  web:
    image: nginx:alpine
    ports:
      - "8080:80"  
    volumes:
      - .:/var/www/php_test
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  
    depends_on:
      - app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_test
    ports:
      - "3306:3306"

  redis:
    image: redis
    ports:
      - "6380:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  
    environment:
      PMA_HOST: db  
      PMA_USER: root
      PMA_PASSWORD: root