version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/var/www/php_test
    depends_on:
      - db
      - redis

  web:
    image: nginx:alpine
    ports:
      - "8080:80"  # Проброс порта 80 контейнера на порт 8080 хоста
    volumes:
      - .:/var/www/php_test
      - ./nginx.conf:/etc/nginx/conf.d/default.conf  # Добавьте файл конфигурации Nginx
    depends_on:
      - app

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: php_test
    ports:
      - "3306:3306"

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Доступ к phpMyAdmin по адресу http://localhost:8081
    environment:
      PMA_HOST: db  # Укажите имя сервиса базы данных
      PMA_USER: root
      PMA_PASSWORD: root